export const NEXT_PLAYER = 'NEXT_PLAYER';
export const SET_PLAYER = 'SET_PLAYER';
export const SET_PLAYER_COLOR = 'SET_PLAYER_COLOR';
export const SET_OPPONENT_COLOR = 'SET_OPPONENT_COLOR';
export const SET_PLAYER_SYMBOL = 'SET_PLAYER_SYMBOL';
export const SET_OPPONENT_SYMBOL = 'SET_OPPONENT_SYMBOL';

//firebase auth
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";